name: etl_tamizajes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0

  # Google & Auth
  google_sign_in: ^7.1.1

  # Gestión de Estado
  provider: ^6.1.2

  # Funcionalidades
  file_picker: ^10.2.0
  excel: ^4.0.2
  archive: ^3.6.1
  crypto: ^3.0.3

  # UI y Navegación
  fl_chart: ^1.0.0
  go_router: ^16.1.0
  cupertino_icons: ^1.0.8
  pluto_grid: ^8.0.0  # <-- PAQUETE AÑADIDO

  # Utilidades
  collection: ^1.18.0
  intl: ^0.19.0 # <-- Se ajusta a una versión compatible
  google_fonts: ^6.2.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Esta sección es la solución al problema.
# Fuerza a todos los paquetes a usar una versión específica de 'intl'.
dependency_overrides:
  intl: 0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
