// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtMpyp2GW_PuE26yRvuxvzZ6nRXlmAJJI',
    appId: '1:802752430955:web:43588180dbdc64d1b4822e',
    messagingSenderId: '802752430955',
    projectId: 'tamizajese-etl',
    authDomain: 'tamizajese-etl.firebaseapp.com',
    storageBucket: 'tamizajese-etl.firebasestorage.app',
    measurementId: 'G-JSKGJLTRDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClH-bkL4V1qfg7OcGDA3nn-aACNzlfpSg',
    appId: '1:802752430955:android:e9235e1d00169940b4822e',
    messagingSenderId: '802752430955',
    projectId: 'tamizajese-etl',
    storageBucket: 'tamizajese-etl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcm7GoUCKDAxcTsYAUnFo8ANYGPc9l4JI',
    appId: '1:802752430955:ios:ecbdd51fc9996601b4822e',
    messagingSenderId: '802752430955',
    projectId: 'tamizajese-etl',
    storageBucket: 'tamizajese-etl.firebasestorage.app',
    iosBundleId: 'com.example.etlTamizajesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcm7GoUCKDAxcTsYAUnFo8ANYGPc9l4JI',
    appId: '1:802752430955:ios:ecbdd51fc9996601b4822e',
    messagingSenderId: '802752430955',
    projectId: 'tamizajese-etl',
    storageBucket: 'tamizajese-etl.firebasestorage.app',
    iosBundleId: 'com.example.etlTamizajesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtMpyp2GW_PuE26yRvuxvzZ6nRXlmAJJI',
    appId: '1:802752430955:web:43588180dbdc64d1b4822e',
    messagingSenderId: '802752430955',
    projectId: 'tamizajese-etl',
    authDomain: 'tamizajese-etl.firebaseapp.com',
    storageBucket: 'tamizajese-etl.firebasestorage.app',
    measurementId: 'G-JSKGJLTRDH',
  );

}